#! /bin/sh
# postinst script for projectlibre

if [ "$1" = "configure" ]; then
	if which update-desktop-database >/dev/null 2>&1 ; then
    	update-desktop-database
	fi	
	if which update-mime-database >/dev/null 2>&1 ; then
    	update-mime-database /usr/share/mime
	fi	
fi